project:
  type: website
  output-dir: ../docs

website:
  title: "MC Coursepack"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Getting Started"
        href: getting-started/getting-started.qmd
      - text: "R & RStudio"
        href: r-and-rstudio/r-and-rstudio.qmd
      - text: "Weekly Journal"
        href: journal/journal-student-guide.qmd
      - text: "Quarto Basics"
        href: quarto/quarto-basics.qmd
      - text: "Course Workflow"
        href: workflow/weekly-workflows.qmd
      - text: "Git & GitHub"
        href: git/git-and-github.qmd
      - text: "Troubleshooting"
        href: troubleshooting/troubleshooting.qmd
      - text: "Reference"
        href: reference/package-reference.qmd

  sidebar:
    - id: getting-started
      title: "Getting Started"
      style: docked
      contents:
        - getting-started/getting-started.qmd
        - getting-started/installation-guide.qmd

    - id: r-and-rstudio
      title: "R & RStudio"
      style: docked
      contents:
        - r-and-rstudio/r-and-rstudio.qmd
        - r-and-rstudio/rstudio-four-panes.qmd
        - r-and-rstudio/rstudio-global-options.qmd
        - r-and-rstudio/r-rstudio-intro-legacy.qmd

    - id: journal
      title: "Weekly Journal"
      style: docked
      contents:
        - journal/journal-student-guide.qmd

    - id: quarto
      title: "Quarto Basics"
      style: docked
      contents:
        - quarto/quarto-basics.qmd

    - id: workflow
      title: "Course Workflow"
      style: docked
      contents:
        - workflow/weekly-workflows.qmd

    - id: git
      title: "Git & GitHub"
      style: docked
      contents:
        - git/git-and-github.qmd
        - git/github-landing-page.qmd
        - git/github-verification.qmd

    - id: troubleshooting
      title: "Troubleshooting"
      style: docked
      contents:
        - troubleshooting/troubleshooting.qmd
        - troubleshooting/pdf-tinytex-errors.qmd
        - troubleshooting/rstudio-older-macs.qmd

    - id: reference
      title: "Reference"
      style: docked
      contents:
        - reference/package-reference.qmd
        - reference/package-functions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-navigation: true
    code-copy: true

execute:
  freeze: auto
  echo: false
  warning: false

