project:
  type: book
  output-dir: docs/textbook
book:
  title: "Introduction to Media and Communications Research Methods"
  author: "A.P. Leith"
  chapters:
    - index.qmd
    - chapter_02.qmd
    - chapter_03.qmd
    - chapter_04.qmd
    - chapter_05.qmd
    - chapter_06.qmd
    - chapter_07.qmd
    - chapter_08.qmd
    - chapter_09.qmd
    - chapter_10.qmd
    - chapter_11.qmd
    - chapter_12.qmd
    - chapter_13.qmd
    - chapter_14.qmd
format:
  pdf:
    toc: true
    number-sections: true
    documentclass: book
    papersize: a4
    mainfont: Public Sans
    sansfont: Public Sans
    fontsize: 11pt
    linestretch: 1.3
    colorlinks: true
    toc-depth: 3
    classoption: [oneside]
    hyperrefoptions: [bookmarksopen=true,bookmarksnumbered=true]
    pdf-engine: lualatex
    keep-tex: false
    include-in-header: |
      \usepackage{fontspec}
      \setmainfont{PublicSans-Regular}[Path=fonts/,Extension=.ttf]
      \setsansfont{PublicSans-Regular}[Path=fonts/,Extension=.ttf]
