project:
  type: book
  output-dir: ../../docs/textbook
book:
  title: "Introduction to Media and Communication Resesarch Methods"
  author: "A.P. Leith"
  chapters:
    - index.qmd
    - chapter_02.qmd
    - chapter_03.qmd
    - chapter_04.qmd
    - chapter_05.qmd
    - chapter_06.qmd
    - chapter_07.qmd
    - chapter_08.qmd
    - chapter_09.qmd
    - chapter_10.qmd
    - chapter_11.qmd
    - chapter_12.qmd
    - chapter_13.qmd
    - chapter_14.qmd
  html:
    theme: cosmo
    css: ../styles.css
    format:
      html:
    freeze: auto
        css: ../styles.css
        toc: true
        page-navigation: true
        code-copy: true
      pdf:
        toc: true
        number-sections: true
        documentclass: book
        papersize: letter
        mainfont: Times New Roman
        sansfont: Arial
        fontsize: 12pt
        linestretch: 1.5
        colorlinks: true
        toc-depth: 3
        classoption: [oneside]
        hyperrefoptions: [bookmarksopen=true,bookmarksnumbered=true]
        pdf-engine: lualatex
        keep-tex: false
  freeze: auto
